version: '3.8'

services:
  medium_post_4:
    container_name: medium-post-4
    build:
      context: .
      dockerfile: awsglue.Dockerfile
    stdin_open: true  # docker run -i
    tty: true # docker run -t
    environment:
      DISABLE_SSL: 'true'
      RAPIDAPI_KEY: ${RAPIDAPI_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCOUND_ID: ${AWS_ACCOUND_ID}
    volumes:
      - .:/home/glue_user/workspace:rw
    network_mode: "host"